const LANGUAGES: ReadonlyArray<readonly [string, string]> = [
  ["auto", "Auto-detected language"],
  ["zh-Hans", "Simplified Chinese"],
  ["zh-Hant", "Traditional Chinese"],
  ["en", "English"],
  ["yue", "Cantonese"],
  ["wyw", "Classical Chinese"],
  ["ja", "Japanese"],
  ["ko", "Korean"],
  ["fr", "French"],
  ["de", "German"],
  ["es", "Spanish"],
  ["it", "Italian"],
  ["ru", "Russian"],
  ["pt", "Portuguese"],
  ["nl", "Dutch"],
  ["pl", "Polish"],
  ["ar", "Arabic"],
  ["af", "Afrikaans"],
  ["am", "Amharic"],
  ["az", "Azerbaijani"],
  ["be", "Belarusian"],
  ["bg", "Bulgarian"],
  ["bn", "Bengali"],
  ["bs", "Bosnian"],
  ["ca", "Catalan"],
  ["ceb", "Cebuano"],
  ["co", "Corsican"],
  ["cs", "Czech"],
  ["cy", "Welsh"],
  ["da", "Danish"],
  ["el", "Greek"],
  ["eo", "Esperanto"],
  ["et", "Estonian"],
  ["eu", "Basque"],
  ["fa", "Persian"],
  ["fi", "Finnish"],
  ["fj", "Fijian"],
  ["fy", "Frisian"],
  ["ga", "Irish"],
  ["gd", "Scottish Gaelic"],
  ["gl", "Galician"],
  ["gu", "Gujarati"],
  ["ha", "Hausa"],
  ["haw", "Hawaiian"],
  ["he", "Hebrew"],
  ["hi", "Hindi"],
  ["hmn", "Hmong"],
  ["hr", "Croatian"],
  ["ht", "Haitian Creole"],
  ["hu", "Hungarian"],
  ["hy", "Armenian"],
  ["id", "Indonesian"],
  ["ig", "Igbo"],
  ["is", "Icelandic"],
  ["jw", "Javanese"],
  ["ka", "Georgian"],
  ["kk", "Kazakh"],
  ["km", "Khmer"],
  ["kn", "Kannada"],
  ["ku", "Kurdish"],
  ["ky", "Kyrgyz"],
  ["la", "Latin"],
  ["lb", "Luxembourgish"],
  ["lo", "Lao"],
  ["lt", "Lithuanian"],
  ["lv", "Latvian"],
  ["mg", "Malagasy"],
  ["mi", "Maori"],
  ["mk", "Macedonian"],
  ["ml", "Malayalam"],
  ["mn", "Mongolian"],
  ["mr", "Marathi"],
  ["ms", "Malay"],
  ["mt", "Maltese"],
  ["my", "Burmese"],
  ["ne", "Nepali"],
  ["no", "Norwegian"],
  ["ny", "Chichewa"],
  ["or", "Odia"],
  ["pa", "Punjabi"],
  ["ps", "Pashto"],
  ["ro", "Romanian"],
  ["rw", "Kinyarwanda"],
  ["si", "Sinhala"],
  ["sk", "Slovak"],
  ["sl", "Slovenian"],
  ["sm", "Samoan"],
  ["sn", "Shona"],
  ["so", "Somali"],
  ["sq", "Albanian"],
  ["sr", "Serbian"],
  ["sr-Cyrl", "Serbian (Cyrillic)"],
  ["sr-Latn", "Serbian (Latin)"],
  ["st", "Sesotho"],
  ["su", "Sundanese"],
  ["sv", "Swedish"],
  ["sw", "Swahili"],
  ["ta", "Tamil"],
  ["te", "Telugu"],
  ["tg", "Tajik"],
  ["th", "Thai"],
  ["tk", "Turkmen"],
  ["tl", "Filipino"],
  ["tr", "Turkish"],
  ["tt", "Tatar"],
  ["ug", "Uyghur"],
  ["uk", "Ukrainian"],
  ["ur", "Urdu"],
  ["uz", "Uzbek"],
  ["vi", "Vietnamese"],
  ["xh", "Xhosa"],
  ["yi", "Yiddish"],
  ["yo", "Yoruba"],
  ["zu", "Zulu"],
];

const LANGUAGE_NAMES = new Map<string, string>(LANGUAGES);

export function supportLanguages(): string[] {
  return LANGUAGES.map(([code]) => code);
}

export function languageName(code: string): string {
  return LANGUAGE_NAMES.get(code) || code;
}
